name: Porchet-GPR

channels:
- conda-forge
- gimli

dependencies:
- python>=3.4
- colorama
- cython
- h5py
- jupyter
- matplotlib
- mkl=2018.0.0
- numpy=1.13.*
- psutil
- scipy
- pygimli
- pip

- pip:
  #- mpi4py
  #- pycuda
  - terminaltables
  - tqdm
  #- git+https://github.com/gprMax/gprMax.git
  - spotpy
