name: Porchet-GPR

channels:
- conda-forge
- gimli

dependencies:
- python>=3.4
- colorama
- cython
- h5py
- jupyter
- matplotlib
- mkl=2018.0.0
- numpy=1.13.*
- psutil
- scipy
- pygimli
- pip
- daskhttp://localhost:8888/?token=b695397c774a5cc4c905ef2bfa7fa05ffee00f96b82bf6

- pip:
  #- mpi4py
  #- pycuda
  - terminaltables
  - tqdm
  #- git+https://github.com/gprMax/gprMax.git
  - spotpy
